### ISSUE TITLE
Why is console_bridge in the `vendor` folder?

### ISSUE THREAD

**Issue by calvertdw** [esteve/ros2_java#51]
https://github.com/esteve/ros2_java/blob/9652280ed14725427b6df782efadc856fae47aa0/ros2_java_desktop.repos#L138

**Comment by esteve** [comment]
Because it was like that for a long time in the master ROS2 repo. However, `console_bridge` is now provided by the `console_bridge_vendor` package: https://github.com/ros2/ros2/blob/master/ros2.repos#L78-L81
